Use `--force` option when uploading cookbooks
This works around the fact that `knife cookbook upload` returns a 0 even
when it fails because of the overwriting of frozen cookbooks. For
example:

```
$ knife cookbook upload oc-lita --freeze --all --config
/var/opt/delivery/workspace/.chef/knife.rb --cookbook-path
/var/opt/delivery/workspace/delivery.chef.co/chef/OCIV/oc-lita/master/build/publish/cache/cookbook-upload
Uploading 7-zip          [1.0.2]
Uploading apt            [2.6.1]
Uploading build-essential [2.1.3]
Uploading chef-sugar     [3.1.0]
Uploading chef_handler   [1.1.6]
Uploading discovery      [0.2.2]
Uploading homebrew       [1.12.0]
Uploading oc-lita        [0.0.2]
Uploading omnibus        [2.6.2]
Uploading redis          [2.1.1]
Uploading runit          [1.5.14]
Uploading stunnel        [2.1.0]
Uploading windows        [1.36.6]
Uploading wix            [1.1.0]
Uploading yum            [3.5.2]
Uploading yum-epel       [0.6.0]
ERROR: Version 1.0.2 of cookbook 7-zip is frozen. Use --force to
override.
WARNING: Not updating version constraints for some cookbooks in the
environment as the cookbook is frozen.
Uploaded all cookbooks.
$ echo $?
0
```

Using the `--force` option should be OK as we want Delivery to fully
control a cookbook and it's dependency list.